Repository stormy-stories-surf/stormy-stories.surf, pull requests merged in 2019-07, with the labels that each got.

#9 added blogpost Brandon Bay / Stradbally
  markdown/posts/2017/ireland-irland/11-05-arrival-ankunft-brandon-bay/de/content.md
  markdown/posts/2017/ireland-irland/11-05-arrival-ankunft-brandon-bay/en/TODO
  markdown/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/de/content.md
  markdown/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/en/TODO
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09040.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09041.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09042.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09050.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09055.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09056.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09060.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09064.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09082.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09098.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09102.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09124.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09129.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09139.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09144.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09145.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09150.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09166.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09178.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09179.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09180.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09183.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09186.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09195.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09206.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09213.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09244.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09250.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09252.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09262.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09267.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09272.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09276.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09288.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09329.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09350.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09393.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09396.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09413.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09439.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09460.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09472.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09497.JPG
  mediaLibrary/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-06-brandon-bay-stradbally-WM-35p-DSC09502.JPG
Labels: enhancement

#39 v0.1.0_38 : delete duplicate picture in ireland-irland/11-06-brandon-…
  markdown/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/de/content.md
Labels: bug

#40 v0.1.0_38 : delete another duplicate picture in ireland-irland/11-06-…
  markdown/posts/2017/ireland-irland/11-06-brandon-bay-stradbally/de/content.md
Labels: bug

#42 Review text
  markdown/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/de/content.md
Labels: enhancement

#34 v0.1.0_30 : 2017/ireland-irland/11-09-magheroarty-beach-donegal-I
  markdown/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/de/content.md
  markdown/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/en/TODO
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09721.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09728.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09744.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09749.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09751.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09756.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09761.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09766.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09773.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09780.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09781.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09782.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09813.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09818.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09823.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09825.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09828.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09830.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09831.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09832.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09870.jpg
  mediaLibrary/posts/2017/ireland-irland/11-09-magheroarty-beach-donegal-I/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-09-magheroarty-beach-donegal-I-WM-35p-DSC09877.jpg
Labels: new blogpost

#33 V0.1.0 29 : 2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore
  markdown/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/de/content.md
  markdown/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/en/TODO
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09529.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09533.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09534.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09536.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09537.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09540.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09543.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09568.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09577.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09586.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09629.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09636.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09645.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09663.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09682.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09685.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09702.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09706.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09707.jpg
  mediaLibrary/posts/2017/ireland-irland/11-07-spanish-point-cliffs-of-moher-mullaghmore/windsurf-stormy-stories-surf-travel-blog-ireland-irland-11-07-spanish-point-cliffs-of-moher-mullaghmore-WM-35p-DSC09710.jpg
Labels: new blogpost

#44 v0.1.0_41 : add text and image to authors page for andre
  markdown/pages/info/authors/de/content.md
  mediaLibrary/pages/info/authors/DSC07571.JPG-50p-1-768x432.jpg
  mediaLibrary/pages/info/authors/avatar-768x432.jpg
  mediaLibrary/pages/info/authors/windsurf-stormy-stories-surf-travel-blog--info-authors-marcel-WM-35p-DSC05577_zuschnitt.jpg
  mediaLibrary/pages/info/authors/windsurf-stormy-stories-surf-travel-blog-info-authors-andre-WM-35p-DSC05582.jpg
  mediaLibrary/pages/info/authors/windsurf-stormy-stories-surf-travel-blog-info-authors-jana-WM-35p-DSC07571.jpg
Labels: enhancement

#48 v0.1.0_35 : add pictures to sticker page
  markdown/pages/info/sticker/de/content.md
  mediaLibrary/pages/info/stickers/windsurf-stormy-stories-surf-travel-blog-info-stickers-WM-35p-DSC05200.jpg
  mediaLibrary/pages/info/stickers/windsurf-stormy-stories-surf-travel-blog-info-stickers-WM-35p-DSC08922_mod.jpg
Labels: enhancement

#49 v0.1.0_41: added text to markdown/pages/info/authors/de/content.md
  markdown/pages/info/authors/de/content.md
Labels: enhancement
